# docker-sftpv2/examples/docker-compose.yml
services:
  sftp:
    image: bmmbmm01/sftp2:latest
    container_name: sftp-fail2ban
    hostname: SFTP
    environment:
      - TZ=America/Chicago
      - AUTO_UPDATE=suite          # none | suite | custom (update the appliation with in the docker...)
      - DEFAULT_ADMIN=true         # seed admin:password on first boot/run in user config file
      - PUID=0
      - PGID=0
      - F2B_CONFIG_MODE=symlink    #Symlink(default), overley, noclober. replace (how to handle the /conf files for fail2ban...)

      #Its better to use the user.conf file in the /config folder... create a default user and passowrd with docker variables...
      #- ADMIN_USER=admin           # optional
      #- ADMIN_PASS=password        # optional (CHANGE THIS!)

      #adational SSHD docker config options... for ssh key connection only.
      # - PASSWORD_AUTH=no         # optional: force pc ssh keys-only
      # - ALLOW_USERS=admin alice  # optional: restrict logins for PC keys

      # TAIL_LOGS: "false"   # optional to turn off logs in the docker log view data. logs still write to logs in container /config/log folder...
      #Not all options listed here....
    logging:  # optional: rotate noisy logs
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
#Optional Unriad Macvlan/IpVlan
#    networks:
#      br0:
#        ipv4_address: 192.168.1.254
#        mac_address: "8a:ad:35:ea:d3:00"
#    dns:
#      - 1.1.1.1
#      - 208.67.222.222
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # App data: supply your custom fail2ban, sshd, users, etc.
      - /mnt/user/appdata:/config
      # User homes to share via SFTP:
      - /data-to-share:/home/admin/sftp 
      # example ssh user folder shared path
    ports:
      - "22:22"  # if not using macvlan and using default docker bridge
    restart: unless-stopped

#Compose connect to ipvlan/macvlan network...
#networks:
#  br0:
#    external: true
