# docker-sftpv2/examples/docker-compose.yml
services:
  sftp:
#    image: WIP... Docker Hub...
    container_name: sftp-fail2ban
    hostname: SFTP
    environment:
      - TZ=America/Chicago
      - AUTO_UPDATE=suite          # none | suite | custom
      - DEFAULT_ADMIN=true         # seed admin:password on first boot
      - PUID=0
      - PGID=0
      #Its better to use the user.conf file in the /config folder...
      #- ADMIN_USER=admin           # optional
      #- ADMIN_PASS=password        # optional (CHANGE THIS!)
      # - PASSWORD_AUTH=no         # optional: force pc ssh keys-only
      # - ALLOW_USERS=admin alice  # optional: restrict logins for PC keys

#    networks:
#      br0:
#        ipv4_address: 192.168.1.254
#        mac_address: "8a:ad:35:ea:d3:00"
    dns:
      - 1.1.1.1
      - 208.67.222.222
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # App data: supply your custom fail2ban, sshd, users, etc.
      - /mnt/vm-zfs/omv/data/sftp:/config
      # User homes to share via SFTP:
      - /data:/home/admin/sftp             # example ssh user folder shared path
    ports:
      - "22:22"                            # if not using macvlan
    restart: unless-stopped

#networks:
#  br0:
#    external: true

